version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0.0
    ports:
      - "9999:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=nvazZn0qUcUnPTwwy66K5zZYuk934S
      - MYSQL_DATABASE=pokemon_db
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-pnvazZn0qUcUnPTwwy66K5zZYuk934S", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql-data:
