version: '3'
services:
  app:
    build: .
    
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=my-secret-pw
      - DB_NAME=pokemon_docker
      - PORT=8080
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0.0
    ports:
      - "9999:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=pokemon_docker
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-pmy-secret-pw", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql-data:
