version: '3'
services:
  app_test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=test
      - DB_HOST=mysql_test
      - DB_USER=root
      - DB_PASS=my-secret-pw
      - DB_NAME=pokemon_test
      - PORT=8080
    depends_on:
      - mysql_test

  mysql_test:
    image: mysql:8.0.0
    ports:
      - "9999:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=pokemon_test
