version: '3'
services:
  app_test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=test
      - DB_HOST=db_test
      - DB_USER=root
      - DB_PASS=vupX{1UN(:j98$,CY=EV9BD=kqQ1
      - DB_NAME=pokemon_test_db
      - PORT=8080
    depends_on:
      db_test:
        condition: service_healthy
        

  db_test:
    image: mysql:8.0.0
    ports:
      - "9999:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=vupX{1UN(:j98$,CY=EV9BD=kqQ1
      - MYSQL_DATABASE=pokemon_test_db
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-pvupX{1UN(:j98$,CY=EV9BD=kqQ1", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
