version: '3'
services:
  app_test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8080:8080"
    env_file:
      - .env.test
    depends_on:
      db_test:
        condition: service_healthy
        

  db_test:
    image: mysql:8.0.0
    ports:
      - "9999:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=EwrpPkTihCcw0fCP64kgwf5PiJCEKV
      - MYSQL_DATABASE=pokemon_test_db
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-pEwrpPkTihCcw0fCP64kgwf5PiJCEKV", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
