# Stage 2: Setup production environment
FROM node:18

WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Copy the rest of your app's source code
COPY . .

# Install only production dependencies
RUN npm install 


# Set the command to start your app
CMD [ "npm", "test" ]
